Cscap 42/fix response
pglob/ocpp-charger-sim pull request #18
Opened 2024-11-18 06:03 UTC by Xerasin

Handle CallResult properly, I was in properly handling everything as a just a Call. I looked closer at the documentation and noted that CallResult is different and does not contain the action name for the message. You are supposed to infer it from the a message we sent and match up the message IDs. I'm not sure I should be deleting the previous messages from hash table, it may be nice to keep it?

2024-11-19 02:10 UTC, pglob approved these changes
Approved with comments

2024-11-19 02:42 UTC, cfarhan commented
I have quite a lot of work done for my CSCAP-51 and CSCAP-53 tickets I'm still working on. This PR might prove to be pretty troublesome if it gets merged before my tickets. Could this wait until after my changes are merged? I'll try to get both merged by Wednesday this week. I also did a bit of code reorganization with packages. 
![image](https://github.com/user-attachments/assets/a2c3698e-e354-44e0-9cde-cfb05fe80066)

2024-11-19 02:55 UTC, cfarhan requested changes
Commenting to prevent this PR from being merged. There are several changes that would break my current tickets I'm working on that I'd like to get merged first before this. I think trying to rebase off master if this ticket got merged would be a total nightmare. Let's hold off on merging this for the time being if that works with everyone.

2024-11-19 03:00 UTC, pglob commented
If this PR, `Cscap 42 Fix CallResult format and add CallError as well; Refactoring included`, extends out into next Sprint, that is okay; We should still be on schedule.

2024-11-19 03:30 UTC, Xerasin commented
> Commenting to prevent this PR from being merged. There are several changes that would break my current tickets I'm working on that I'd like to get merged first before this. I think trying to rebase off master if this ticket got merged would be a total nightmare. Let's hold off on merging this for the time being if that works with everyone.

That was my plan!

2024-11-19 04:10 UTC, Xerasin commented on backend/src/main/java/com/sim_backend/websockets/OCPPWebSocketClient.java
>    public void onMessage(String s) {
I catch all of them now and print a message to the stderr instead.

2024-11-22 22:30 UTC, cfarhan approved these changes

2024-11-23 00:21 UTC, merged