CSCAP71/Add Authorization Observer
pglob/ocpp-charger-sim pull request #34
Opened 2024-12-08 21:32 UTC by JayQuack

Authorization Observer Added
Testing "Accepted", "Blocked" status
I think it's going to work, let me know if there is any possible improvement.

2024-12-08 21:59 UTC, JayQuack commented
I have deleted void onAuthorizeReceived(AuthorizeResponse response); from OnOCPPMessageListener interface due to error

2024-12-08 23:02 UTC, cfarhan commented
I think each individual message type needs its own MessageHandler class, or observer class, however you want to phrase it. As in, your code should be in its own "AuthorizeHandler" or "AuthorizeObserver". The current implementation will require that ALL of the individual response work must be done in onMessage found in OCPPMessageHandler, which kind of defeats the purpose of the OCPPMessageListener interface imo. @pglob @Xerasin Would like to know your insights to this. Have 

On another note I've been bogged down with other classes but will try to get my boot observer ticket out tonight. The structure of the observers might make more sense once I get a PR out.

2024-12-10 05:55 UTC, pglob commented
> I think each individual message type needs its own MessageHandler class, or observer class, however you want to phrase it. As in, your code should be in its own "AuthorizeHandler" or "AuthorizeObserver". The current implementation will require that ALL of the individual response work must be done in onMessage found in OCPPMessageHandler, which kind of defeats the purpose of the OCPPMessageListener interface imo.

Agreed, the observer needs to be in its own class. We want to avoid monoliths for processing messages as they will mostly have unique logic.

The observer can be created and registered in our main.

2024-12-10 06:10 UTC, pglob requested changes

2024-12-10 06:10 UTC, pglob commented on backend/src/main/java/com/sim_backend/websockets/observer/AuthorizeObserver.java
> +  private List<OCPPMessageHandler> observers = new ArrayList<>();
Observers should not be tracked/registered separately here. The WebSocket client has a function that allows for registering observers already (see `OCPPWebSocketClient.java`). Just register this observer in our main.

2024-12-10 06:10 UTC, pglob commented on backend/src/main/java/com/sim_backend/websockets/exceptions/IllegalAuthorizeResponse.java
> +public class IllegalAuthorizeResponse extends RuntimeException {
I don't think this is required. Issues with serializing / empty messages should be handled by the WebSocket client code. If I'm missing something and it is required, document the reasoning in the code like other exceptions.

2024-12-10 17:07 UTC, JayQuack commented
Cameron helped me to understand the concept, thanks !

2024-12-11 00:44 UTC, pglob requested changes

2024-12-11 00:44 UTC, pglob commented on backend/src/main/java/com/sim_backend/websockets/observers/AuthorizeObserver.java
Add javadoc comments

2024-12-11 00:44 UTC, pglob commented on backend/src/main/java/com/sim_backend/websockets/observers/AuthorizeObserver.java
> +  public void handleAuthorize(OCPPWebSocketClient client, AuthorizeResponse response) {
Per the OCPP spec, the Authorize operation is only initiated by the charge point. Therefore, our simulator will never send an `AuthorizeResponse` message. 

Instead, this function can just send an `Authorize` message.

2024-12-13 23:13 UTC, pglob approved these changes
Approved with a comment.

2024-12-13 23:13 UTC, pglob commented on backend/src/test/java/com/sim_backend/websockets/observers/AuthorizeObserverTest.java
> +  void testAuthorizeMessage() {
Capture output from `onMessageReceived` and assert that it matches the expected message. You can get a stream with something like
`private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();`
 `System.setOut(new PrintStream(outContent));`
from the java.io.ByteArrayOutputStream, and java.io.PrintStream libraries.

2024-12-14 16:34 UTC, merged